spring.application.name=checkout-service
server.port=8091
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=config-service
spring.config.import=optional:configserver:
eureka.instance.hostname=localhost

loadbalancer.client.name=products-service

# OAuth2 Resource Server JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8081/realms/dh

resilience4j.circuitbreaker.instances.product.allowHealthIndicatorToFail = false
resilience4j.circuitbreaker.instances.product.registerHealthIndicator= true


resilience4j.circuitbreaker.instances.product.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.product.slidingWindowSize = 5
resilience4j.circuitbreaker.instances.product.failureRateThreshold= 50


resilience4j.circuitbreaker.instances.product.waitDurationInOpenState = 15000
resilience4j.circuitbreaker.instances.product.permittedNumberOfCallsInHalfOpenState = 3
resilience4j.circuitbreaker.instances.product.automaticTransitionFromOpenToHalfOpenEnabled = true




