spring.application.name=checkout-service
server.port=8091
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=config-service
spring.config.import=optional:configserver:
eureka.instance.hostname=localhost

loadbalancer.client.name=products-service

# OAuth2 Resource Server JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8081/realms/dh